name: Scrape Heureka Wishlist

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'
    
    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install firefox-geckodriver
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4
    
    - name: Run scraper
      env:
        HEUREKA_EMAIL: ${{ secrets.HEUREKA_EMAIL }}
        HEUREKA_PASSWORD: ${{ secrets.HEUREKA_PASSWORD }}
      run: python scraper.py --force-refresh
